[package]
name = "core"
version = "0.1.0"
authors = ["Ivan Kalinin <i.kalinin@dexpa.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]

[dependencies]
base64 = "0.13"
js-sys = "0.3"
syn = "=1.0.64"
wasm-bindgen = { version = "=0.2.70", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
wee_alloc = "0.4"

ton_types = { git = "https://github.com/tonlabs/ton-labs-types.git" }

[target."cfg(debug_assertions)".dependencies]
console_error_panic_hook = "0.1"

[dev-dependencies]
wasm-bindgen-test = "0.3"
js-sys = "0.3"
wasm-bindgen-futures = "0.4"
